routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/','TareasController@index')->name('inicio');
Route::resource('tarea','TareasController');
//Route::get('tarea','TareasController');
Route::post('tarea/{tarea}','TareasController@update')->name('tareaUpdate');
Route::get('tarea/bigrama/local','TareasController@bigrama')->name('tarea.bigrama');

Route::get('tarea/trigrama/local','TareasController@trigrama')->name('tarea.trigrama');
Route::get('tarea/markov/vitorama','TareasController@markov')->name('tarea.markov');
Route::get('tarea/markov/mapacaracteres','TareasController@mapacaracteres')->name('tarea.mapacaracteres');
Route::get('tarea/markov/oracionnumeracion','TareasController@oracionnumeracion')->name('tarea.oracionnumeracion');





Route::get('tarea/operacion/suma','TareasController@operacionessuma')->name('operaciones.suma');
Route::get('tarea/operacion/resta','TareasController@operacionesresta')->name('operaciones.resta');
Route::get('tarea/operacion/multplicacion','TareasController@operacionesmultip')->name('operaciones.multplicacion');
Route::get('tarea/operacion/division','TareasController@operacionesdivisi')->name('operaciones.division');
Route::get('tarea/operacion/variable','TareasController@operacionesvariable')->name('operaciones.variable');
Route::get('tarea/operacion/basura','TareasController@operacionesbasura')->name('operaciones.basura');
Route::get('tarea/basura/index','TareasController@Tareasbasura')->name('basura');


Route::get('tarea/hmm/index','TareasController@devolvertablaHMM')->name('devolvertablahmm');
Route::get('tarea/hmm/suma','TareasController@devolvertablaHMMsuma')->name('devolvertablahmmsuma');
Route::get('tarea/hmm/resta','TareasController@devolvertablaHMMresta')->name('devolvertablahmmresta');
Route::get('tarea/hmm/multipli','TareasController@devolvertablaHMMmultipli')->name('devolvertablahmmmultipli');
Route::get('tarea/hmm/divisi','TareasController@devolvertablaHMMdivisi')->name('devolvertablahmmdivisi');
Route::get('tarea/hmm/basura','TareasController@devolvertablaHMMbasur')->name('devolvertablahmmbasura');
Route::get('tarea/hmm/vector','TareasController@devolvertablaHMMvector')->name('devolvertablahmmvector');

app/Tareas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tareas extends Model
{
    protected $fillable = [
        'titulo', 'descripcion', 'nivel_de_prioridad','operacion',
    ];

    protected $primaryKey = 'id_tarea';
    public $timestamps = false;
}

app/Http/Controllers/TareasController.php
<?php

namespace App\Http\Controllers;

use App\bigrama;
use App\cantpalaclavevalor;
use App\information;
use App\mapacaracteres;
use App\oracionnumeracion;
use App\tablahmmmodel;
use App\tareaba;
use App\Tareas;
use App\trigrama;
use Illuminate\Http\Request;

class TareasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $task = Tareas::all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.index')->with('task', $task)->with('information', $info);
        //
    }



    public function Tareasbasura()
    {
        $task = tareaba::all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.basura')->with('task', $task)->with('information', $info);
        //
    }



    public function bigrama()
    {

        $task = bigrama::all();

        return view('tareas.indexbigrama')->with('task', $task);
    }

    public function trigrama()
    {

        $task = trigrama::all();

        return view('tareas.indextrigrama')->with('task', $task);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tareas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tareas = new Tareas();
        $tareas->titulo = $request->titulo;
        $tareas->descripcion = $request->descripcion;
        $tareas->nivel_de_prioridad = $request->nivel_de_prioridad;
        $tareas->save();

        return redirect('tarea');
    }

    public function markov()
    {
        $palabrascantidad = cantpalaclavevalor::all();

        return view('tareas.PalabrasCantidad')->with('palaabras', $palabrascantidad);
    }



    public function mapacaracteres()
    {
        $mapacaracteres = mapacaracteres::all();

        return view('tareas.PalabrasCantidad')->with('palaabras', $mapacaracteres);
    }


    public function oracionnumeracion()
    {
        $oracionnumeracion = oracionnumeracion::all();

        return view('tareas.oracionnumeracion')->with('palaabras', $oracionnumeracion);
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Tareas $tareas
     * @return \Illuminate\Http\Response
     */
    public function show(Tareas $tareas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tareas $tareas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tarea = Tareas::where("id_tarea", '=', $id)->first();

        return view('tareas.edit', compact('tarea'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Tareas $tareas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //$this->validate($request,[ 'nombre'=>'required', 'resumen'=>'required', 'npagina'=>'required', 'edicion'=>'required', 'autor'=>'required', 'npagina'=>'required', 'precio'=>'required']);
        $tarea = Tareas::where('id_tarea', '=', $id)->first();

//$estructura->idEstructura=$request->$idEstructura;
        $tarea->update([
            $tarea->id_tarea = $id,
            $tarea->titulo = $request->titulo,
            $tarea->descripcion = $request->descripcion,
            $tarea->nivel_de_prioridad = $request->nivel_de_prioridad,
            //$tarea->Nombre=$request->personal,
            //$tarea->Puesto=$request->Puesto,
            //$tarea->FotoPresidente=$request->fichero

        ]);

        return redirect('tarea');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tareas $tareas
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Tareas::find($id)->delete();

        return response()->json([
            'result' => 'ok',
        ]);
    }

    public function operacionessuma(Request $request)
    {
        $operaciones =Tareas::all();
        $suma=$operaciones->where('operacion','=','suma')->all();

        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.opsuma')->with('task',$suma )->with('information',$info);

    }



    public function operacionesresta(Request $request)
    {
        $operaciones =Tareas::all();
        $resta=$operaciones->where('operacion','=','resta')->all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.opresta')->with('task',$resta )->with('information',$info);

    }


    public function operacionesmultip(Request $request)
    {
        $operaciones =Tareas::all();
        $multiplicar=$operaciones->where('operacion','=','multiplicar')->all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.opmultiplica')->with('task',$multiplicar )->with('information',$info);

    }




    public function operacionesdivisi(Request $request)
    {
        $operaciones =Tareas::all();
        $division=$operaciones->where('operacion','=','dividir')->all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.opdivide')->with('task',$division )->with('information',$info);

    }


    public function operacionesvariable(Request $request)
    {
        $operaciones =Tareas::all();
        $vector=$operaciones->where('operacion','=','vector')->all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.opvector')->with('task',$vector )->with('information',$info);

    }

    public function operacionesbasura(Request $request)
    {
        $operaciones =Tareas::all();
        $basura=$operaciones->where('operacion','=','NS')->all();
        $informatione = information::all();
        $info = $informatione->last();

        return view('tareas.opbasura')->with('task',$basura )->with('information',$info);

    }

    public function devolvertablaHMM(Request $request)
{

    $task=tablahmmmodel::all();
    return view('tareas.indextablahmm')->with('task',$task);

}

public function devolvertablaHMMsuma(Request $request)
{

    $task=tablahmmmodel::all();
    $taske=$task->where('descripcion','=','suma')->all();
    return view('tareas.indextablahmmsuma')->with('task',$taske);

}



    public function devolvertablaHMMresta(Request $request)
    {

        $task=tablahmmmodel::all();
        $taske=$task->where('descripcion','=','resta')->all();
        return view('tareas.indextablahmmresta')->with('task',$taske);

    }


    public function devolvertablaHMMmultipli(Request $request)
    {

        $task=tablahmmmodel::all();
        $taske=$task->where('descripcion','=','multiplicar')->all();
        return view('tareas.indextablahmmmultipli')->with('task',$taske);

    }


    public function devolvertablaHMMdivisi(Request $request)
    {

        $task=tablahmmmodel::all();
        $taske=$task->where('descripcion','=','dividir')->all();
        return view('tareas.indextablahmmdivisi')->with('task',$taske);

    }

    public function devolvertablaHMMbasur(Request $request)
    {

        $task=tablahmmmodel::all();
        $taske=$task->where('descripcion','=','NS')->all();
        return view('tareas.indextablahmmbasur')->with('task',$taske);

    }  public function devolvertablaHMMvector(Request $request)
    {

        $task=tablahmmmodel::all();
        $taske=$task->where('descripcion','=','vector')->all();
        return view('tareas.indextablahmmvector')->with('task',$taske);

    }
}

resources/views/tareas/basura.blade.php
@extends('app')

@section('content')

    {{--<div class="container">--}}
        <div class="row">
<div class="container">
            <p></p>
            <h1>Corpus Matemático cuenta con  {{$information->cantpalabra}} palabras totales </h1>
            <p>EL Corpus matemático esta compuesto por {{$information->cantpalabrasdiferentes}} palabras diferentes y {{$information->cantoracionesdiferetes}} sentencias ademas esta la basura que son las cosas basura.</p>
            {{--<p>A simple example of how-to put a bordered table within a panel. Responsive, place holders in header/footer for buttons or pagination.</p>--}}
            {{--<p>Siguelo  <a href="https://twitter.com/asked_io" target="_new">@asked_io</a> & <a href="https://asked.io/" target="_new">asked.io</a>.</p>--}}
            <p> </p><p> </p>
</div>
            <div class="col-md-10 col-md-offset-1">

                <div class="panel panel-default panel-table">
                    <div class="panel-heading" style="margin-bottom: 1em">
                        <div class="row">
                            <div class="col col-xs-6">
                                <h3 class="panel-title">Corpus Matemático</h3>
                            </div>
                            <div class="col col-xs-6 text-right">
                                <a type="button" href="{{route('tarea.create')}}" class="btn btn-sm btn-primary btn-create">Crear</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table  id="example" class="table table-striped table-bordered table-list">
                            <thead>
                            <tr>
                                <th><em class="fa fa-cog"></em></th>
                                <th class="hidden-xs">ID</th>
                                <th> Titulo </th>
                                <th>Descripcion </th>
                                <th>Prioridad</th>
                                <th>Operación</th>
                                <th>Basura</th>


                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($task as $item)
                            <tr>
                                <td align="center">
                                    <a class="btn btn-default"    href="{{action('TareasController@edit', $item->id_tarea)}}"> <em class="fa fa-pencil"></em></a>


                                    <a class="btn btn-danger"  onclick="eliminarusuarioid({{$item->id_tarea}})"> <em class="fa fa-trash"></em></a>
                                </td>
                                <td class="hidden-xs">{{$item->id_tarea}}</td>
                                <td>{{$item->titulo}} 	</td>
                                <td>{{$item->descripcion }} 	</td>
                                <td>{{$item->nivel_de_prioridad}} 	</td>
                                <td>{{$item->operacion}} 	</td>
                                <td>{{$item->basura}} 	</td>

                            </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                    {{--<div class="panel-footer">--}}
                        {{--<div class="row">--}}
                            {{--<div class="col col-xs-4">Page 1 of 5--}}
                            {{--</div>--}}
                            {{--<div class="col col-xs-8">--}}
                                {{--<ul class="pagination hidden-xs pull-right">--}}
                                    {{--<li><a href="#">1</a></li>--}}
                                    {{--<li><a href="#">2</a></li>--}}
                                    {{--<li><a href="#">3</a></li>--}}
                                    {{--<li><a href="#">4</a></li>--}}
                                    {{--<li><a href="#">5</a></li>--}}
                                {{--</ul>--}}
                                {{--<ul class="pagination visible-xs pull-right">--}}
                                    {{--<li><a href="#">«</a></li>--}}
                                    {{--<li><a href="#">»</a></li>--}}
                                {{--</ul>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</div>--}}


            </div></div>
    </div>

    {{--{{$task}}--}}


    <script>

        function eliminarusuarioid(usuario_id) {
            // alert(usuario_id);


            swal({
                title: "Esta Seguro?",
                text: "Una vez eliminado, no podrá recuperar la estructura!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {


                        // var responsable = usuario_id;

                        // var usuario_ide=usuario_id;
                        $.ajax({
                            url: "tarea/" + usuario_id,
                            {{--url: "{{route('estructura/'+ usuario_ide)}}",--}}
                            data: "&_token={{ csrf_token()}}",
                            dataType: "json",
                            method: "DELETE",
                            success: function (result) {
                                if (result['result'] == 'ok') {

                                    swal("Poof! ¡La estructura ha sido eliminada!", {
                                        icon: "success",
                                        timer: 2500,
                                    });
                                    setTimeout(location.reload.bind(location), 2500);
// if (swal.close()) {
//
//
// }
                                    // location.reload();

                                    // cachan.delay('10000');


                                    // setTimeout(location.reload(),);


                                }
                                else {

                                }
                            },
                            fail: function () {
                            },
                            beforeSend: function () {
                            }
                        });


                        // $.ajax({
                        //
                        //     type: 'GET',
                        //     data: { responsable: usuario_id },
                        //     url: '@Url.Action("CargarResponsa", "RC_Volantes")',
                        //     success: function (result) {
                        //
                        //         var s = '<option value="-1">ESCOGE LA ZONA</option>';
                        //         for (var i = 0; i < result.length; i++) {
                        //             s += '<option value="' + result[i].Id + '">' + result[i].Name + '</option>';
                        //             $('#OtroResponsable').html(s);
                        //         }
                        //
                        //
                        //     }
                        //
                        // });


                    } else {
                        swal("La Estructura no se eliminó");
                    }
                });

            // $("#ide2").attr("value", usuario_id);


        }
    </script>
    @endsection

resources/views/tareas/indexbigrama.blade.php
@extends('app')

@section('content')

    {{--<div class="container">--}}
        <div class="row">
<div class="container">
            <p></p>
            <h1>Análisis de los bigramas cantidad de bigramas del corpus</h1>
            <p>Un bigrama o digrama es un grupos de dos letras, dos sílabas, o dos palabras. Los bigramas son utilizados comúnmente como base para el simple análisis estadístico de texto. Se utilizan en uno de los más exitosos modelos de lenguaje para el reconocimiento de voz.​ Se trata de un caso especial del N-grama.</p>
            {{--<p>Follow me <a href="https://twitter.com/asked_io" target="_new">@asked_io</a> & <a href="https://asked.io/" target="_new">asked.io</a>.</p>--}}
            <p> </p><p> </p>
</div>
            <div class="col-md-10 col-md-offset-1">

                <div class="panel panel-default panel-table">
                    <div class="panel-heading" style="margin-bottom: 1em">
                        <div class="row">
                            <div class="col col-xs-6">
                                <h3 class="panel-title">Bigramas</h3>
                            </div>
                            <div class="col col-xs-6 text-right">
                                <a type="button" href="{{route('tarea.create')}}" class="btn btn-sm btn-primary btn-create">Crear</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table  id="example1" class="table table-striped table-bordered table-list">
                            <thead>
                            <tr>
                                <th><em class="fa fa-cog"></em></th>
                                <th class="hidden-xs">ID</th>
                                <th> Clave </th>
                                <th>Valor </th>
                                <th>Descripcion</th>
                                <th>Cantidad</th>


                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($task as $item)
                            <tr>
                                <td align="center">
                                    <a class="btn btn-default"    href="{{action('TareasController@edit', $item->id)}}"> <em class="fa fa-pencil"></em></a>


                                    <a class="btn btn-danger"  onclick="eliminarusuarioid({{$item->id}})"> <em class="fa fa-trash"></em></a>
                                </td>
                                <td class="hidden-xs">{{$item->id}}</td>
                                <td>{{$item->clave}} 	</td>
                                <td>{{$item->valor}} 	</td>
                                <td>{{$item->descripcion}} 	</td>
                                <td>{{$item->cantidad}} 	</td>

                            </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                    {{--<div class="panel-footer">--}}
                        {{--<div class="row">--}}
                            {{--<div class="col col-xs-4">Page 1 of 5--}}
                            {{--</div>--}}
                            {{--<div class="col col-xs-8">--}}
                                {{--<ul class="pagination hidden-xs pull-right">--}}
                                    {{--<li><a href="#">1</a></li>--}}
                                    {{--<li><a href="#">2</a></li>--}}
                                    {{--<li><a href="#">3</a></li>--}}
                                    {{--<li><a href="#">4</a></li>--}}
                                    {{--<li><a href="#">5</a></li>--}}
                                {{--</ul>--}}
                                {{--<ul class="pagination visible-xs pull-right">--}}
                                    {{--<li><a href="#">«</a></li>--}}
                                    {{--<li><a href="#">»</a></li>--}}
                                {{--</ul>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</div>--}}


            </div></div>
    </div>

    {{--{{$task}}--}}


    <script>

        function eliminarusuarioid(usuario_id) {
            // alert(usuario_id);


            swal({
                title: "Esta Seguro?",
                text: "Una vez eliminado, no podrá recuperar la estructura!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {


                        // var responsable = usuario_id;

                        // var usuario_ide=usuario_id;
                        $.ajax({
                            url: "tarea/" + usuario_id,
                            {{--url: "{{route('estructura/'+ usuario_ide)}}",--}}
                            data: "&_token={{ csrf_token()}}",
                            dataType: "json",
                            method: "DELETE",
                            success: function (result) {
                                if (result['result'] == 'ok') {

                                    swal("Poof! ¡La estructura ha sido eliminada!", {
                                        icon: "success",
                                        timer: 2500,
                                    });
                                    setTimeout(location.reload.bind(location), 2500);
// if (swal.close()) {
//
//
// }
                                    // location.reload();

                                    // cachan.delay('10000');


                                    // setTimeout(location.reload(),);


                                }
                                else {

                                }
                            },
                            fail: function () {
                            },
                            beforeSend: function () {
                            }
                        });


                        // $.ajax({
                        //
                        //     type: 'GET',
                        //     data: { responsable: usuario_id },
                        //     url: '@Url.Action("CargarResponsa", "RC_Volantes")',
                        //     success: function (result) {
                        //
                        //         var s = '<option value="-1">ESCOGE LA ZONA</option>';
                        //         for (var i = 0; i < result.length; i++) {
                        //             s += '<option value="' + result[i].Id + '">' + result[i].Name + '</option>';
                        //             $('#OtroResponsable').html(s);
                        //         }
                        //
                        //
                        //     }
                        //
                        // });


                    } else {
                        swal("La Estructura no se eliminó");
                    }
                });

            // $("#ide2").attr("value", usuario_id);


        }
    </script>
    @endsection